### ISSUE TITLE
UI looks weird when no reviews/ 

### ISSUE THREAD

**Issue by jiaawe** [waisheen/foodies#53]
![image](https://user-images.githubusercontent.com/99934518/179411085-1619efea-a4f0-42d3-ac54-363eb6aa4e01.png)

**Comment by k5924** [comment]
I'm not sure where to code is for the reviews but I am assuming that you wouldn't want the View all reviews text button to load if there are no reviews on the page. 
If the text button is in the same stateful widget as the widget builder, you could conditionally render the text button by checking if the count of reviews is greater than 0:
```dart
reviews.count() != 0 ? TextButton("View all reviews", (){}) : Container()
```

If the reviews are loaded in a separate widget and the text button is in a different widget, you could either:
1. raise the state of when the reviews are loaded so that the reviews are first retrieved in the parent widget holding the reviews widget and the TextButton widget, passing the retrieved reviews object to the widget builder to display reviews and using the conditional above to render the TextButton dynamically or 
2. call the widget builder for reviews and have that child widget return the review count to the parent widget and catch the returned object in the parent widget to then conditionally render the TextButton.

I would recommend option 1 if this is the issue you have with the UI. If this isn't the issue that you have with the UI then please elaborate.

**Comment by k5924** [comment]
After reviewing your code, I believe it would be easier to raise the state of the getReviewSnapshots function so that it is called inside of the ShopDetailsPage instead of the ShowReviewPage, the snapshot can then be passed to the ShowReviewPage and inside the ShopDetailsPage, you can check if the snapshot has any data to conditionally render the View All Reviews container.
